import '../../core/resources/constants.dart';

Map<int, String> weatherConditions = {
  1: 'Clear',
  2: 'Fair',
  3: 'Cloudy',
  4: 'Overcast',
  5: 'Fog',
  6: 'Freezing Fog',
  7: 'Light Rain',
  8: 'Rain',
  9: 'Heavy Rain',
  10: 'Freezing Rain',
  11: 'Heavy Freezing Rain',
  12: 'Sleet',
  13: 'Heavy Sleet',
  14: 'Light Snowfall',
  15: 'Snowfall',
  16: 'Heavy Snowfall',
  17: 'Rain Shower',
  18: 'Heavy Rain Shower',
  19: 'Sleet Shower',
  20: 'Heavy Sleet Shower',
  21: 'Snow Shower',
  22: 'Heavy Snow Shower',
  23: 'Lightning',
  24: 'Hail',
  25: 'Thunderstorm',
  26: 'Heavy Thunderstorm',
  27: 'Storm',
};

Map<int, String> weatherConditionsImages = {
  1: ImagesKeys.sunny,
  2: ImagesKeys.sunny,
  3: ImagesKeys.partiallyCloudy,
  4: ImagesKeys.partiallyCloudy,
  5: ImagesKeys.cloudy,
  6: ImagesKeys.cloudy,
  7: ImagesKeys.rainPartiallyCloudy,
  8: ImagesKeys.rain,
  9: ImagesKeys.rain,
  10: ImagesKeys.rain,
  11: ImagesKeys.rain,
  12: ImagesKeys.rain,
  13: ImagesKeys.rain,
  14: ImagesKeys.rain,
  15: ImagesKeys.rain,
  16: ImagesKeys.rain,
  17: ImagesKeys.rain,
  18: ImagesKeys.rain,
  19: ImagesKeys.rain,
  20: ImagesKeys.rain,
  21: ImagesKeys.rain,
  22: ImagesKeys.rain,
  23: ImagesKeys.rain,
  24: ImagesKeys.rain,
  25: ImagesKeys.rain,
  26: ImagesKeys.rain,
  27: ImagesKeys.rain,
};
